
export const ANNOUNCEMENTDATA = [
    {
        id: 1,
        title: "There is no Sore it will Not Heal, No cool it will not Subdue.",

    },
    {
        id: 2,
        title: "coziness building for tomorrow",

    },
    {
        id: 3,
        title: "There is no Sore it will Not Heal, No cool it will not Subdue.",

    },
    {
        id: 4,
        title: "Review the facts cool is the best.",

    },
    {
        id: 5,
        title: "Review the facts cool is the best.",

    },
    {
        id: 6,
        title: "coziness building for tomorrow",

    },
    {
        id: 7,
        title: "There is no Sore it will Not Heal, No cool it will not Subdue.",

    },
    {
        id: 8,
        title: "coziness building for tomorrow",

    },
    {
        id: 9,
        title: "There is no Sore it will Not Heal, No cool it will not Subdue.",

    },
    {
        id: 10,
        title: "coziness building for tomorrow",

    },
    {
        id: 11,
        title: "There is no Sore it will Not Heal, No cool it will not Subdue.",

    },
    {
        id: 12,
        title: "coziness building for tomorrow",

    },
    {
        id: 13,
        title: "There is no Sore it will Not Heal, No cool it will not Subdue.",

    },
    {
        id: 14,
        title: "coziness building for tomorrow",

    },
    {
        id: 15,
        title: "There is no Sore it will Not Heal, No cool it will not Subdue.",

    },
    {
        id: 16,
        title: "coziness building for tomorrow",

    },
    {
        id: 17,
        title: "There is no Sore it will Not Heal, No cool it will not Subdue.",

    },
    {
        id: 18,
        title: "coziness building for tomorrow",

    },
];

export const CTADATA = [
    {
        id: 1,
        title: "Search",
        image: './images/cta1.png',
        content: "Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.",
    },
    {
        id: 2,
        title: "Select",
        image: './images/cta2.png',
        content: "Choose from thousands of options generated by the slogan maker that fit your needs.",
    },
    {
        id: 3,
        title: "Stand out",
        image: './images/cta3.png',
        content: "Congrats on your new slogan. It's time to win the world!",
    },
]
export const PRODDATA = [
    {
        id: 1,
        title: "Privacy Policy Generator",
        image: './images/prod1.png',
        content: "Stock your store with 100s of products and start selling to customers in minutes, without the hassle of inventory or packaging.",
    },
    {
        id: 2,
        title: "Terms & Conditions Generator",
        image: './images/prod3.png',
        content: "Stock your store with 100s of products and start selling to customers in minutes, without the hassle of inventory or packaging.",
    },
    {
        id: 3,
        title: "Domain Name Generator",
        image: './images/prod4.png',
        content: "Stock your store with 100s of products and start selling to customers in minutes, without the hassle of inventory or packaging.",
    },
    {
        id: 4,
        title: "Invoice Generator",
        image: './images/prod5.png',
        content: "Stock your store with 100s of products and start selling to customers in minutes, without the hassle of inventory or packaging.",
    },

]